services:
  vpn-gateway:
    container_name: vpn-gateway
    image: qmcgaw/gluetun
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - '/dev/net/tun:/dev/net/tun'
    ports:
      - 9091:9091/tcp
      - 51413:51413/tcp
      - 51413:51413/udp
    volumes:
      - ../volumes/vpn:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=openvpn
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - SERVER_COUNTRIES=${VPN_COUNTRIES}
      - TZ='${TIMEZONE}'
      - UPDATER_PERIOD='24h'
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
